export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OFFICE_BOY = 'OFFICE_BOY',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD',
}

export enum AssetStatus {
  AVAILABLE = 'AVAILABLE',
  ASSIGNED = 'ASSIGNED',
  RETURNED = 'RETURNED',
  DAMAGED = 'DAMAGED',
  UNDER_REPAIR = 'UNDER_REPAIR',
  LOST = 'LOST',
}

export enum CourierStatus {
  SUBMITTED = 'SUBMITTED',
  BOOKED = 'BOOKED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  COMPLETED = 'COMPLETED',
}

export enum AmcStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  RENEWED = 'RENEWED',
  CLOSED = 'CLOSED',
}

export enum PgStatus {
  ACTIVE = 'ACTIVE',
  EXPIRED = 'EXPIRED',
  RENEWED = 'RENEWED',
  CLOSED = 'CLOSED',
}

export enum NotificationType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  REQUEST_UPDATED = 'REQUEST_UPDATED',
  REQUEST_COMPLETED = 'REQUEST_COMPLETED',
  ASSET_ASSIGNED = 'ASSET_ASSIGNED',
  COURIER_DELIVERY = 'COURIER_DELIVERY',
  LOW_STOCK = 'LOW_STOCK',
  CONTRACT_EXPIRY = 'CONTRACT_EXPIRY',
  ACCOMMODATION_EXPIRY = 'ACCOMMODATION_EXPIRY',
  ATTENDANCE_CORRECTION_REQUEST = 'ATTENDANCE_CORRECTION_REQUEST',
  ATTENDANCE_CORRECTION_APPROVED = 'ATTENDANCE_CORRECTION_APPROVED',
  ATTENDANCE_CORRECTION_REJECTED = 'ATTENDANCE_CORRECTION_REJECTED',
  GENERAL = 'GENERAL',
}

export enum AttendanceStatus {
  PRESENT = 'PRESENT',
  FULL_DAY = 'FULL_DAY',
  HALF_DAY = 'HALF_DAY',
  EARLY_LEAVE = 'EARLY_LEAVE',
  ABSENT = 'ABSENT',
  PARTIAL = 'PARTIAL',
  LATE = 'LATE',
  INCOMPLETE = 'INCOMPLETE',
  REJECTED_LOCATION = 'REJECTED_LOCATION',
  HOLIDAY = 'HOLIDAY',
}

export enum AttendanceCorrectionType {
  PRESENT_FULL_DAY = 'PRESENT_FULL_DAY',
  PRESENT_FULL_DAY_NOT_COMPLETED_9H = 'PRESENT_FULL_DAY_NOT_COMPLETED_9H',
  PRESENT_HALF_DAY = 'PRESENT_HALF_DAY',
  ABSENT_INFORMED_SENIOR = 'ABSENT_INFORMED_SENIOR',
  HOLIDAY = 'HOLIDAY',
}

export enum AttendanceCorrectionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AttendanceActivityType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  LOGIN_LOCATION_REJECTED = 'LOGIN_LOCATION_REJECTED',
  LOGOUT_LOCATION_REJECTED = 'LOGOUT_LOCATION_REJECTED',
  LOGIN_LOCATION_PERMISSION_DENIED = 'LOGIN_LOCATION_PERMISSION_DENIED',
  LOGOUT_LOCATION_PERMISSION_DENIED = 'LOGOUT_LOCATION_PERMISSION_DENIED',
  LOGIN_ALREADY_ACTIVE = 'LOGIN_ALREADY_ACTIVE',
  LOGOUT_WITHOUT_LOGIN = 'LOGOUT_WITHOUT_LOGIN',
  LOGOUT_ALREADY_COMPLETED = 'LOGOUT_ALREADY_COMPLETED',
}
